"use strict";

const assert = require('assert');
var request = require("request");

const extKey = 'aa39b5490c4a4ed0e56d7ec1232a428f771e8bb83cfcee16de14f735d0f5da587d5968ec4f785e38570902fd24e0b522b46cb171872d1ea038e88328e7d973ff47d9392f72b2d49566209eb88eb60aed8534a965cf30072c39565bd8d72f68ac';

function executeMyRequest(params, apiPath, method, cb) {
    requester(apiPath, method, params, function (error, body) {
        assert.ifError(error);
        assert.ok(body);
        return cb(body);
    });

    function requester(apiName, method, params, cb) {
        var options = {
            uri: 'http://localhost:4000/dashboard/' + apiName,
            headers: {
                'Content-Type': 'application/json',
                key: extKey
            },
            json: true
        };

        if (params.headers) {
            for (var h in params.headers) {
                if (params.headers.hasOwnProperty(h)) {
                    options.headers[h] = params.headers[h];
                }
            }
        }

        if (params.form) {
            options.body = params.form;
        }

        if (params.qs) {
            options.qs = params.qs;
        }

        request[method](options, function (error, response, body) {
            assert.ifError(error);
            assert.ok(body);
            return cb(null, body);
        });
    }
}

let catalog = {
    "name": "testCatalog",
    "type": "service",
    "description": "This is a catalog for testing purposes.",
    "recipe": {
        "deployOptions" : {
            "image": {
                "prefix": "soajstest",
                "name": "newSoajs",
                "tag": "latest",
            },
            "ports": [
                {
                    "name": "servicePort",
                    "isPublished": true,
                    "target": 84
                }
            ],
        }
    }
};

let catalogId = null;
let lockedId = null;

let params = {};
//Begin testing
describe("Testing Catalog Functionality", function() {

    describe("Testing Catalog ADD API", function(){
        //Attempt to add a catalog that contains an invalid property
        //The result should be an error generated by the IMFV
        it("Fail - Add an invalid catalog", function (done) {
            catalog.invalidProperty = "invalidProperty";

            params = {
                "form": {
                    "catalog": catalog
                }
            };

            executeMyRequest(params, "catalog/recipes/add", 'post', function (result) {
                assert.ok(result.errors);
                assert.deepEqual(result.errors.details[0], {
                    "code": 173,
                    "message": "Validation failed for field: catalog -> The parameter 'catalog' failed due to: instance additionalProperty \"invalidProperty\" exists in instance when not allowed"
                });

                done();
            });
        });

        //Attempt to add a catalog that contains a valid schema
        it("Success - Add a valid catalog", function (done){

            delete catalog.invalidProperty;
            //the API will delete this property
            catalog.locked = true;

            params = {
                "form": {
                    "catalog": catalog
                }
            };

            executeMyRequest(params, "catalog/recipes/add", 'post', function (result) {
                assert.ok(result.data);
                assert.ok(result.result);
                done();
            });
        });
    });

    describe("Testing Catalog LIST API", function() {
        //List available catalogs
        it("Success - List available catalogs", function (done) {
            params = {};

            executeMyRequest(params, "catalog/recipes/list", 'get', function (records) {
                //get the IDs of the catalogs for later use;
                records.data.forEach(function (oneRecord) {
                    if (oneRecord.name === "lockedCatalog")
                        lockedId = oneRecord._id;
                    else if(oneRecord.name === "testCatalog")
                        catalogId = oneRecord._id
                });

                assert.ok(records.data);
                assert.ok(records.data.length > 0);
                done();
            });
        });
    });

    describe("Testing Catalog EDIT API", function() {
        //Edit a record that doesn't exist
        it("Fail - Edit a record that doesn't exist", function (done) {
            params = {
                "qs": {
                    "id": "invalidId"
                },
                "form": {
                    "catalog": catalog
                }
            };

            executeMyRequest(params, "catalog/recipes/update", 'put', function (result) {
                assert.ok(result.errors);
                assert.deepEqual(result.errors.details[0], {
                    "code": 701,
                    "message": "Invalid Id provided"
                });
                done();
            });
        });

        //Edit a locked record
        it("Fail - Edit a locked catalog", function (done) {
            params = {
                "qs": {
                    "id": lockedId
                },
                "form": {
                    "catalog": catalog
                }
            };

            executeMyRequest(params, "catalog/recipes/update", 'put', function (result) {
                assert.ok(result.errors);
                assert.deepEqual(result.errors.details[0], {
                    "code": 951,
                    "message": "You are not allowed to edit or delete a locked recipe"
                });
                done();
            });
        });

        //Edit a valid unlocked record
        it("Success - Edit a record", function (done) {
            catalog.recipe.buildOptions = {
                "env": {
                    "SOAJS_ENV_1": {
                        "type": "computed",
                        "default": "SOAJS_ENV_1"
                    },
                    "SOAJS_ENV_2": {
                        "type": "computed",
                        "default": "SOAJS_ENV_2"
                    },
                    "SOAJS_ENV_3": {
                        "type": "computed",
                        "default": "SOAJS_ENV_3"
                    },
                }
            };
            params = {
                "qs": {
                    "id": catalogId
                },
                "form": {
                    "catalog": catalog,
                }
            };

            executeMyRequest(params, "catalog/recipes/update", 'put', function (result) {
                assert.ok(result.data);
                assert.ok(result.result);
                done();
            });
        });
    });
	
	describe("Testing Catalog GET API", function(){
		it("fail - invalid catalog id", function(done){
			params = {
				"qs": {
					"id": "invalidId"
				}
			};
			
			executeMyRequest(params, "catalog/recipes/get", 'get', function (result) {
				assert.ok(result.errors);
				assert.deepEqual(result.errors.details[0], {
					"code": 701,
					"message": "Invalid Id provided"
				});
				done();
			});
		});
		
		it("success- valid catalog id", function(done){
			params = {
				"qs": {
					"id": catalogId
				}
			};
			
			executeMyRequest(params, "catalog/recipes/get", 'get', function (result) {
				assert.ok(result.data);
				done();
			});
		});
	});
	
    describe("Testing Catalog DELETE API", function() {
        //Delete a record that doesn't exist
        it("Fail - Delete a record that doesn't exist", function (done) {
            params = {
                "qs": {
                    "id": "invalidId"
                }
            };

            executeMyRequest(params, "catalog/recipes/delete", 'delete', function (result) {
                assert.ok(result.errors);
                assert.deepEqual(result.errors.details[0], {
                    "code": 701,
                    "message": "Invalid Id provided"
                });
                done();
            });
        });


        //Delete a locked record
        it("Fail - Delete a locked record", function (done) {
            params = {
                "qs": {
                    "id": lockedId
                }
            };

            executeMyRequest(params, "catalog/recipes/delete", 'delete', function (result) {
                assert.ok(result.errors);
                assert.deepEqual(result.errors.details[0], {
                    "code": 951,
                    "message": "You are not allowed to edit or delete a locked recipe"
                });
                done();
            });
        });

        //Delete a valid unlocked record
        it("Success - Delete a record", function (done) {
            params = {
                "qs": {
                    "id": catalogId
                }
            };

            executeMyRequest(params, "catalog/recipes/delete", 'delete', function (result) {
                assert.ok(result.data);
                assert.ok(result.result);
                done();
            });
        });
    });
	
});